//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gladiator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_cities
    {
        public int id { get; set; }
        public string city_name { get; set; }
        public string city_code { get; set; }
        public string state_code { get; set; }
    
        public virtual all_states all_states { get; set; }
    }
}
