//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gladiator.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Document
    {
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string Aadhar { get; set; }
        [DataMember]
        public string PAN { get; set; }
        [DataMember]
        public string TraderLi { get; set; }
        [DataMember]
        public string CertificateFarmer { get; set; }
        [DataMember]
        public bool ApproveStatus { get; set; }
    }
}
