//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gladiator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveBid
    {
        public Nullable<int> CropId { get; set; }
        public double BasePrice { get; set; }
        public double BidPrice { get; set; }
        public bool BidStatus { get; set; }
        public string Bemail { get; set; }
        public Nullable<int> TransBidID { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public int BidId { get; set; }
    
        public virtual Bidder Bidder { get; set; }
        public virtual CropBuy CropBuy { get; set; }
        public virtual CropSell CropSell { get; set; }
    }
}
