//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gladiator.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Transaction
    {
        [DataMember]
        public string PaymentType { get; set; }
        [DataMember]
        public System.DateTime Date { get; set; }
        [DataMember]
        public Nullable<int> BidID { get; set; }
        [DataMember]
        public int TransactioID { get; set; }
    
        public virtual CropBuy CropBuy { get; set; }
    }
}
