export class ViewBidder{
    Name;
    Bemail;
    ContactNo;
    Address;
    City;
    State;
    PIN;
    AccNo;
    IFSC;
    Aadhar;
    PAN;
    TraderLi;
    
    constructor(){
        this.Name="";
        this.Bemail="";
        this.ContactNo="";
        this.Address="";
        this.City="";
        this.State="";
        this.PIN="";
        this.AccNo="";
        this.IFSC="";
        this.Aadhar="";
        this.PAN="";
        this.TraderLi="";
    }
}