export class ViewFarmer{
    Name;
    Femail;
    ContactNo;
    Address;
    City;
    State;
    PIN;
    AccNo;
    IFSC;
    Aadhar;
    PAN;
    CertificateFarmer;
    
    constructor(){
        this.Name="";
        this.Femail="";
        this.ContactNo="";
        this.Address="";
        this.City="";
        this.State="";
        this.PIN="";
        this.AccNo="";
        this.IFSC="";
        this.Aadhar="";
        this.PAN="";
        this.CertificateFarmer="";
    }
}